### ISSUE TITLE
EFI Support

### ISSUE THREAD

**Issue by Thesola10** [Leurak/MEMZ#11]
Maybe port the Nyan payload to EFI aswell? Replacing bootmgr.efi files in the bootloader partition should do the trick.

**Comment by Leurak** [comment]
Will try that if I got time. I think I'll start doing one last version of MEMZ, reimplementing everything.

I never used the EFI API, but I think it's a lot easier than the classic BIOS Interrupts, so I hope it won't get that hard.

I also hope that overwriting the EFI bootloader is easy. I guess secure boot would screw it anyway, but some systems do not have secure boot enabled by default. Secure boot systems will just skip the overwriting then, as I'm planning to do an automated recovery function.

**Comment by Thesola10** [comment]
I tried UEFI programming and well... it's different. It's way more managed than direct MBR execution, obviously, and also surprisingly C++ centric. I'm not a fan of that practice but since it's the market standatd... Oh and they also [got rid of their own Secure Boot](https://arstechnica.com/security/2016/08/microsoft-secure-boot-firmware-snafu-leaks-golden-key/) so that could be useful

**Comment by Leurak** [comment]
I think implementing support for EFI actually isn't that good of an idea. It would never run on secure boot, had to be completely rewritten, due to the way EFI works and I bet Windows would not easily allow you to overwrite the EFI bootloader.

The best way would be just leaving the partition table intact, allowing UEFI systems to still boot instead of having to recover it manually (remember, a recovery feature inside the MBR payload should get implemented that wouldn't work in this case)
