### ISSUE TITLE
exe2bat.py fails

### ISSUE THREAD

**Issue by Wasserboy08** [Leurak/MEMZ#16]
using: python 2.7 on 32bit vista
![image](https://cloud.githubusercontent.com/assets/22521667/24105767/385f777e-0d86-11e7-847d-0abcd49d2586.png)

**Comment by mmgordon82** [comment]
I think you forgot to add python as the first word.
without it, the arguments wont pass to sys.argv.

**Comment by Leurak** [comment]
You need to pass 3 or 4 arguments. The first one is the input file, the second the output file and the third one specifies the name of the EXE integrated into the batch file.

The fourth is just for the method if you specify it.

`-zip` is only useful for executables which aren't already compressed. If it's random or already compressed, it will increase the file size.

`-xp` uses the same script as `-zip`, but does not compress. It's still XP compatible.

Without a fourth argument, it will use a tool available since Vista, but it does not include a script so it can be the smallest option if the file is not well compressable.

Also keep in mind that the files won't run on Windows 98, if that's your intention.

By the way, you can convert any file into a bat. You can even convert things like a JPEG into a bat. But it will load a long time if the file is too big.
